### ISSUE TITLE
您好，请问安装paddleclas这一步如果是win11系统的话需要在paddlepaddle虚拟环境下进行pip安装

### ISSUE THREAD

**Issue by zhanghangzzz** [cnhemiya/shitu-manager#3]
用的miniconda,已经装好了paddlepaddle
![image](https://user-images.githubusercontent.com/128710784/227888678-cca6add3-6833-4dbf-9ce9-5f930a5dec14.png)

**Comment by cnhemiya** [comment]
如果是conda环境，就要在conda里安装paddlepadle和paddleclas

**Comment by zhanghangzzz** [comment]
> 如果是conda环境，就要在conda里安装paddlepadle和paddleclas

好的，谢谢，已经解决了
