### ISSUE TITLE
你好，执行命令后无反应是什么原因

### ISSUE THREAD

**Issue by zhanghangzzz** [cnhemiya/shitu-manager#5]
win11系统，用miniconda安装的paddlepaddle环境，在终端运行paddleclas的检测算法是没有问题的，但执行命令后无反应。
![image](https://user-images.githubusercontent.com/128710784/234572829-7b193910-6084-4a1e-b12a-46940f36182b.png)

**Comment by cnhemiya** [comment]
依赖安装了没有

**Comment by zhanghangzzz** [comment]
> 依赖安装了没有
你好，在终端执行了pip命令，应该是全部安装了
![image](https://user-images.githubusercontent.com/128710784/235162508-54081fdf-15a1-4ebf-968b-8e8d9f812cad.png)

**Comment by cnhemiya** [comment]
这个不清楚了。最上面的你执行也没出错信息，不好推测

**Comment by zhanghangzzz** [comment]
> 这个不清楚了。 最上面的你执行也没出错信息，不好推测

好的，麻烦了，我再看看

**Comment by zhanghangzzz** [comment]
> 这个不清楚了。 最上面的你执行也没出错信息，不好推测

找到问题了，由于是win11系统，我用了python 代替了python3命令就解决了，谢谢了
